# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HwSgnVnPLBKV-x3Wo7LVAHtD8G-SbLQy
"""

# prompt: from textblob import TextBlob
# import matplotlib.pyplot as plt
# # Sample list of social media conversations
# social_media_posts = [
#     "I love the new features in this app!",
#     "This update is terrible. It ruined everything.",
#     "I'm not sure how I feel about this update.",
#     "Best day ever! Thank you for the amazing experience.",
#     "I'm so disappointed with the service lately.",
# ]
# # Function to analyze sentiment and collect counts
# def analyze_sentiment(posts):
#     sentiment_counts = {"Positive": 0, "Negative": 0, "Neutral": 0}
#     for post in posts:
#         blob = TextBlob(post)
#         sentiment_score = blob.sentiment.polarity
#         if sentiment_score > 0:
#             sentiment = "Positive"
#         elif sentiment_score < 0:
#             sentiment = "Negative"
#         else:
#             sentiment = "Neutral"
#         sentiment_counts[sentiment] += 1
#         print(f"Post: {post}\nSentiment: {sentiment} (Score: {sentiment_score})\n")
#     # Plotting the bar chart
#     plt.bar(sentiment_counts.keys(), sentiment_counts.values(), color=['green', 'red', 'gray'])
#     plt.title("Sentiment Analysis of Social Media Posts")
#     plt.xlabel("Sentiment")
#     plt.ylabel("Number of Posts")
#     plt.show()
# # Run the analysis
# analyze_sentiment(social_media_posts)

from textblob import TextBlob
import matplotlib.pyplot as plt

# Sample list of social media conversations (provided in the prompt)
social_media_posts = [
    "I love the new features in this app!",
    "This update is terrible. It ruined everything.",
    "I'm not sure how I feel about this update.",
    "Best day ever! Thank you for the amazing experience.",
    "I'm so disappointed with the service lately.",
]

# Function to analyze sentiment and collect counts (provided in the prompt)
def analyze_sentiment(posts):
    sentiment_counts = {"Positive": 0, "Negative": 0, "Neutral": 0}
    for post in posts:
        blob = TextBlob(post)
        sentiment_score = blob.sentiment.polarity
        if sentiment_score > 0:
            sentiment = "Positive"
        elif sentiment_score < 0:
            sentiment = "Negative"
        else:
            sentiment = "Neutral"
        sentiment_counts[sentiment] += 1
        print(f"Post: {post}\nSentiment: {sentiment} (Score: {sentiment_score})\n")

    # Plotting the bar chart
    plt.bar(sentiment_counts.keys(), sentiment_counts.values(), color=['green', 'red', 'gray'])
    plt.title("Sentiment Analysis of Social Media Posts")
    plt.xlabel("Sentiment")
    plt.ylabel("Number of Posts")
    plt.show()

# Run the analysis (provided in the prompt)
analyze_sentiment(social_media_posts)